backend:
  name: git-gateway
  repo: JSG-12/proratronic

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.njk" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Hero Button Text", name: "hero_button_text", widget: "string" }
          - { label: "Hero Button Link", name: "hero_button_link", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "_data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Features", name: "features", widget: "list", fields: [{ label: "Feature", name: "feature", widget: "string" }] }
      - { label: "Image", name: "image", widget: "image" }
